<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>Prophecy.Integration</AssemblyName>
    <Version>1.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OmenCore.Core\OmenCore.Core.csproj" />
    <InternalsVisibleTo Include="OmenCoreApp.Tests" />
    <InternalsVisibleTo Include="OmenCore" />
  </ItemGroup>
</Project>
